package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/PeterTakahashi/commitlog-ai/internal/model"
)

// ExportMarkdown writes the timeline to a single Markdown file.
func ExportMarkdown(timeline model.LinkedTimeline, outputDir string) (string, error) {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", fmt.Errorf("creating output directory: %w", err)
	}

	outPath := filepath.Join(outputDir, "timeline.md")

	var b strings.Builder

	// Header
	repoName := filepath.Base(timeline.GitRepo)
	b.WriteString(fmt.Sprintf("# commitlog-ai — %s\n\n", repoName))
	b.WriteString(fmt.Sprintf("> Generated by [commitlog-ai](https://github.com/PeterTakahashi/commitlog-ai) on %s\n\n", time.Now().Format("2006-01-02 15:04")))

	// Summary
	linked, commitOnly, sessionOnly := 0, 0, 0
	agentCounts := make(map[string]int)
	for _, e := range timeline.Entries {
		if e.Commit != nil && e.Session != nil {
			linked++
		} else if e.Commit != nil {
			commitOnly++
		} else {
			sessionOnly++
		}
		if e.Session != nil {
			agentCounts[e.Session.Agent.Tool]++
		}
	}

	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Metric | Count |\n"))
	b.WriteString(fmt.Sprintf("|--------|-------|\n"))
	b.WriteString(fmt.Sprintf("| Total entries | %d |\n", len(timeline.Entries)))
	b.WriteString(fmt.Sprintf("| Linked (commit + session) | %d |\n", linked))
	b.WriteString(fmt.Sprintf("| Commit only | %d |\n", commitOnly))
	b.WriteString(fmt.Sprintf("| Session only | %d |\n", sessionOnly))
	for agent, count := range agentCounts {
		b.WriteString(fmt.Sprintf("| %s sessions | %d |\n", agentLabel(agent), count))
	}
	b.WriteString("\n---\n\n")

	// Group entries by date
	groups := groupByDate(timeline.Entries)
	for _, g := range groups {
		b.WriteString(fmt.Sprintf("## %s\n\n", g.date))

		for _, e := range g.entries {
			writeEntry(&b, e)
		}
	}

	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("writing %s: %w", outPath, err)
	}

	return outPath, nil
}

func writeEntry(b *strings.Builder, e model.TimelineEntry) {
	if e.Commit != nil && e.Session != nil {
		// Linked entry
		c := e.Commit
		s := e.Session
		confidence := int(e.LinkConfidence * 100)

		b.WriteString(fmt.Sprintf("### `%s` %s\n\n", c.Hash[:7], c.Message))
		b.WriteString(fmt.Sprintf("- **Agent**: %s (`%s`)\n", agentLabel(s.Agent.Tool), s.Agent.Model))
		b.WriteString(fmt.Sprintf("- **Confidence**: %d%%\n", confidence))
		b.WriteString(fmt.Sprintf("- **Time**: %s — %s\n", s.StartedAt.Format("15:04"), s.EndedAt.Format("15:04")))
		b.WriteString(fmt.Sprintf("- **Changes**: %d file(s), +%d -%d\n", c.FilesChanged, c.Additions, c.Deletions))
		if len(c.ChangedFiles) > 0 {
			b.WriteString(fmt.Sprintf("- **Files**: `%s`\n", strings.Join(truncateList(c.ChangedFiles, 8), "`, `")))
		}
		b.WriteString("\n")

		// Conversation summary (first human message + first assistant response)
		writeConversationSummary(b, s.Messages)
		b.WriteString("\n---\n\n")

	} else if e.Commit != nil {
		// Commit only
		c := e.Commit
		b.WriteString(fmt.Sprintf("### `%s` %s\n\n", c.Hash[:7], c.Message))
		b.WriteString(fmt.Sprintf("- **Author**: %s\n", c.Author))
		b.WriteString(fmt.Sprintf("- **Changes**: %d file(s), +%d -%d\n", c.FilesChanged, c.Additions, c.Deletions))
		b.WriteString(fmt.Sprintf("- *No agent session linked*\n"))
		b.WriteString("\n---\n\n")

	} else if e.Session != nil {
		// Session only
		s := e.Session
		b.WriteString(fmt.Sprintf("### Session: %s (%s)\n\n", agentLabel(s.Agent.Tool), s.Agent.Model))
		b.WriteString(fmt.Sprintf("- **Time**: %s — %s\n", s.StartedAt.Format("15:04"), s.EndedAt.Format("15:04")))
		b.WriteString(fmt.Sprintf("- **Messages**: %d\n", len(s.Messages)))
		b.WriteString(fmt.Sprintf("- *No commit linked*\n"))
		b.WriteString("\n")
		writeConversationSummary(b, s.Messages)
		b.WriteString("\n---\n\n")
	}
}

func writeConversationSummary(b *strings.Builder, messages []model.Message) {
	if len(messages) == 0 {
		return
	}

	b.WriteString("<details>\n<summary>Conversation</summary>\n\n")

	for _, msg := range messages {
		if msg.Content == "" && len(msg.ToolCalls) == 0 {
			continue
		}

		if msg.Role == "human" {
			b.WriteString("**You:**\n\n")
		} else {
			b.WriteString("**Assistant:**\n\n")
		}

		if msg.Content != "" {
			// Truncate very long messages (rune-aware to avoid splitting multi-byte chars)
			content := msg.Content
			runes := []rune(content)
			if len(runes) > 2000 {
				content = string(runes[:2000]) + "\n\n*(truncated)*"
			}
			b.WriteString(content)
			b.WriteString("\n\n")
		}

		for _, tc := range msg.ToolCalls {
			b.WriteString(fmt.Sprintf("*Tool: `%s`*\n\n", tc.Tool))
		}
	}

	b.WriteString("</details>\n")
}

func agentLabel(tool string) string {
	switch tool {
	case "claude_code":
		return "Claude"
	case "gemini_cli":
		return "Gemini"
	case "codex_cli":
		return "Codex"
	default:
		return tool
	}
}

type dateGroup struct {
	date    string
	entries []model.TimelineEntry
}

func groupByDate(entries []model.TimelineEntry) []dateGroup {
	var groups []dateGroup
	seen := make(map[string]int) // date -> index in groups

	for _, e := range entries {
		var ts time.Time
		if e.Commit != nil {
			ts = e.Commit.Timestamp
		} else if e.Session != nil {
			ts = e.Session.StartedAt
		} else {
			continue
		}

		date := ts.Format("2006-01-02 (Mon)")
		idx, ok := seen[date]
		if !ok {
			idx = len(groups)
			seen[date] = idx
			groups = append(groups, dateGroup{date: date})
		}
		groups[idx].entries = append(groups[idx].entries, e)
	}

	return groups
}

func truncateList(items []string, max int) []string {
	if len(items) <= max {
		return items
	}
	result := items[:max]
	result = append(result, fmt.Sprintf("... +%d more", len(items)-max))
	return result
}
